version: "3.8"
services:
  redis:
    image: redislabs/redismod
    expose:
      - 6379
  app:
    build: app
    ports:
      - 9700:9700
    links:
      - redis
    environment:
      - REDIS_URL=redis
  proxy:
    build: proxy
    ports:
      - 8080:8080
    links:
      - app