version: "3.8"
services:
  redis:
    image: redislabs/redismod
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
    links:
      - redis
  app:
    build: app
    ports:
      - 9700:9700
    links:
      - redis
    environment:
      - REDIS_URL=redis
  proxy:
    build: proxy
    ports:
      - 8080:8080
    links:
      - app
volumes:
  redis_data: