# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import network_pb2 as network__pb2


class UserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/protobuf.User/CreateUser',
                request_serializer=network__pb2.NewUserRequest.SerializeToString,
                response_deserializer=network__pb2.NewUserResponse.FromString,
                )
        self.GetUser = channel.unary_unary(
                '/protobuf.User/GetUser',
                request_serializer=network__pb2.GetUserDetailsRequest.SerializeToString,
                response_deserializer=network__pb2.GetUserDetailsResponse.FromString,
                )
        self.SearchForUser = channel.unary_unary(
                '/protobuf.User/SearchForUser',
                request_serializer=network__pb2.SearchUserRequest.SerializeToString,
                response_deserializer=network__pb2.SearchUserResponse.FromString,
                )
        self.CreateFriendship = channel.unary_unary(
                '/protobuf.User/CreateFriendship',
                request_serializer=network__pb2.CreateFriendshipRequest.SerializeToString,
                response_deserializer=network__pb2.CreateFriendshipResponse.FromString,
                )
        self.ReplyToFriendship = channel.unary_unary(
                '/protobuf.User/ReplyToFriendship',
                request_serializer=network__pb2.FriendshipReplyRequest.SerializeToString,
                response_deserializer=network__pb2.FriendshipReplyResponse.FromString,
                )


class UserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchForUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFriendship(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplyToFriendship(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=network__pb2.NewUserRequest.FromString,
                    response_serializer=network__pb2.NewUserResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=network__pb2.GetUserDetailsRequest.FromString,
                    response_serializer=network__pb2.GetUserDetailsResponse.SerializeToString,
            ),
            'SearchForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchForUser,
                    request_deserializer=network__pb2.SearchUserRequest.FromString,
                    response_serializer=network__pb2.SearchUserResponse.SerializeToString,
            ),
            'CreateFriendship': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFriendship,
                    request_deserializer=network__pb2.CreateFriendshipRequest.FromString,
                    response_serializer=network__pb2.CreateFriendshipResponse.SerializeToString,
            ),
            'ReplyToFriendship': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplyToFriendship,
                    request_deserializer=network__pb2.FriendshipReplyRequest.FromString,
                    response_serializer=network__pb2.FriendshipReplyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protobuf.User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class User(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.User/CreateUser',
            network__pb2.NewUserRequest.SerializeToString,
            network__pb2.NewUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.User/GetUser',
            network__pb2.GetUserDetailsRequest.SerializeToString,
            network__pb2.GetUserDetailsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.User/SearchForUser',
            network__pb2.SearchUserRequest.SerializeToString,
            network__pb2.SearchUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateFriendship(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.User/CreateFriendship',
            network__pb2.CreateFriendshipRequest.SerializeToString,
            network__pb2.CreateFriendshipResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplyToFriendship(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.User/ReplyToFriendship',
            network__pb2.FriendshipReplyRequest.SerializeToString,
            network__pb2.FriendshipReplyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ItemStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitItem = channel.unary_unary(
                '/protobuf.Item/SubmitItem',
                request_serializer=network__pb2.SubmitItemRequest.SerializeToString,
                response_deserializer=network__pb2.SubmitItemResponse.FromString,
                )
        self.SubmitItemOffer = channel.unary_unary(
                '/protobuf.Item/SubmitItemOffer',
                request_serializer=network__pb2.ItemOfferRequest.SerializeToString,
                response_deserializer=network__pb2.ItemOfferResponse.FromString,
                )


class ItemServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitItemOffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ItemServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitItem': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitItem,
                    request_deserializer=network__pb2.SubmitItemRequest.FromString,
                    response_serializer=network__pb2.SubmitItemResponse.SerializeToString,
            ),
            'SubmitItemOffer': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitItemOffer,
                    request_deserializer=network__pb2.ItemOfferRequest.FromString,
                    response_serializer=network__pb2.ItemOfferResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protobuf.Item', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Item(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Item/SubmitItem',
            network__pb2.SubmitItemRequest.SerializeToString,
            network__pb2.SubmitItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubmitItemOffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Item/SubmitItemOffer',
            network__pb2.ItemOfferRequest.SerializeToString,
            network__pb2.ItemOfferResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class NetworkStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNetwork = channel.unary_unary(
                '/protobuf.Network/CreateNetwork',
                request_serializer=network__pb2.NewNetworkRequest.SerializeToString,
                response_deserializer=network__pb2.NewNetworkResponse.FromString,
                )
        self.GetNetworksForUser = channel.unary_unary(
                '/protobuf.Network/GetNetworksForUser',
                request_serializer=network__pb2.NetworksForUserRequest.SerializeToString,
                response_deserializer=network__pb2.NetworksForUserResponse.FromString,
                )
        self.SearchForNetworks = channel.unary_unary(
                '/protobuf.Network/SearchForNetworks',
                request_serializer=network__pb2.SearchForNetworksRequest.SerializeToString,
                response_deserializer=network__pb2.SearchForNetworksResponse.FromString,
                )
        self.InviteUserToNetwork = channel.unary_unary(
                '/protobuf.Network/InviteUserToNetwork',
                request_serializer=network__pb2.InviteUserToNetworkRequest.SerializeToString,
                response_deserializer=network__pb2.InviteUserToNetworkResponse.FromString,
                )
        self.ReplyToNetworkInvite = channel.unary_unary(
                '/protobuf.Network/ReplyToNetworkInvite',
                request_serializer=network__pb2.NetworkInviteReplyRequest.SerializeToString,
                response_deserializer=network__pb2.NetworkInviteReplyResponse.FromString,
                )


class NetworkServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNetworksForUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchForNetworks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InviteUserToNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplyToNetworkInvite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NetworkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNetwork,
                    request_deserializer=network__pb2.NewNetworkRequest.FromString,
                    response_serializer=network__pb2.NewNetworkResponse.SerializeToString,
            ),
            'GetNetworksForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetworksForUser,
                    request_deserializer=network__pb2.NetworksForUserRequest.FromString,
                    response_serializer=network__pb2.NetworksForUserResponse.SerializeToString,
            ),
            'SearchForNetworks': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchForNetworks,
                    request_deserializer=network__pb2.SearchForNetworksRequest.FromString,
                    response_serializer=network__pb2.SearchForNetworksResponse.SerializeToString,
            ),
            'InviteUserToNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.InviteUserToNetwork,
                    request_deserializer=network__pb2.InviteUserToNetworkRequest.FromString,
                    response_serializer=network__pb2.InviteUserToNetworkResponse.SerializeToString,
            ),
            'ReplyToNetworkInvite': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplyToNetworkInvite,
                    request_deserializer=network__pb2.NetworkInviteReplyRequest.FromString,
                    response_serializer=network__pb2.NetworkInviteReplyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protobuf.Network', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Network(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/CreateNetwork',
            network__pb2.NewNetworkRequest.SerializeToString,
            network__pb2.NewNetworkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNetworksForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/GetNetworksForUser',
            network__pb2.NetworksForUserRequest.SerializeToString,
            network__pb2.NetworksForUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchForNetworks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/SearchForNetworks',
            network__pb2.SearchForNetworksRequest.SerializeToString,
            network__pb2.SearchForNetworksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InviteUserToNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/InviteUserToNetwork',
            network__pb2.InviteUserToNetworkRequest.SerializeToString,
            network__pb2.InviteUserToNetworkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplyToNetworkInvite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/ReplyToNetworkInvite',
            network__pb2.NetworkInviteReplyRequest.SerializeToString,
            network__pb2.NetworkInviteReplyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
