# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import network_pb2 as network__pb2


class NetworkStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveImage = channel.unary_unary(
                '/protobuf.Network/SaveImage',
                request_serializer=network__pb2.SaveImageRequest.SerializeToString,
                response_deserializer=network__pb2.SaveImageResponse.FromString,
                )
        self.GetImage = channel.unary_unary(
                '/protobuf.Network/GetImage',
                request_serializer=network__pb2.GetImageRequest.SerializeToString,
                response_deserializer=network__pb2.GetImageResponse.FromString,
                )
        self.CreateUser = channel.unary_unary(
                '/protobuf.Network/CreateUser',
                request_serializer=network__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=network__pb2.CreateUserResponse.FromString,
                )
        self.GetUser = channel.unary_unary(
                '/protobuf.Network/GetUser',
                request_serializer=network__pb2.GetUserRequest.SerializeToString,
                response_deserializer=network__pb2.GetUserResponse.FromString,
                )
        self.SubmitItem = channel.unary_unary(
                '/protobuf.Network/SubmitItem',
                request_serializer=network__pb2.SubmitItemRequest.SerializeToString,
                response_deserializer=network__pb2.SubmitItemResponse.FromString,
                )
        self.SubmitItemOffer = channel.unary_unary(
                '/protobuf.Network/SubmitItemOffer',
                request_serializer=network__pb2.SubmitItemOfferRequest.SerializeToString,
                response_deserializer=network__pb2.SubmitItemOfferResponse.FromString,
                )
        self.CreateNetwork = channel.unary_unary(
                '/protobuf.Network/CreateNetwork',
                request_serializer=network__pb2.CreateNetworkRequest.SerializeToString,
                response_deserializer=network__pb2.CreateNetworkResponse.FromString,
                )
        self.GetNetworksForUser = channel.unary_unary(
                '/protobuf.Network/GetNetworksForUser',
                request_serializer=network__pb2.GetNetworksForUserRequest.SerializeToString,
                response_deserializer=network__pb2.GetNetworksForUserResponse.FromString,
                )
        self.GetItemsForUser = channel.unary_unary(
                '/protobuf.Network/GetItemsForUser',
                request_serializer=network__pb2.GetItemsForUserRequest.SerializeToString,
                response_deserializer=network__pb2.GetItemsForUserResponse.FromString,
                )
        self.GetItemsForNetwork = channel.unary_unary(
                '/protobuf.Network/GetItemsForNetwork',
                request_serializer=network__pb2.GetItemsForNetworkRequest.SerializeToString,
                response_deserializer=network__pb2.GetItemsForNetworkResponse.FromString,
                )
        self.JoinNetwork = channel.unary_unary(
                '/protobuf.Network/JoinNetwork',
                request_serializer=network__pb2.JoinNetworkRequest.SerializeToString,
                response_deserializer=network__pb2.JoinNetworkResponse.FromString,
                )
        self.GetOffersForUserItems = channel.unary_unary(
                '/protobuf.Network/GetOffersForUserItems',
                request_serializer=network__pb2.GetOffersForUserItemsRequest.SerializeToString,
                response_deserializer=network__pb2.GetOffersForUserItemsResponse.FromString,
                )
        self.GetOffersMadeByUser = channel.unary_unary(
                '/protobuf.Network/GetOffersMadeByUser',
                request_serializer=network__pb2.GetOffersMadeByUserRequest.SerializeToString,
                response_deserializer=network__pb2.GetOffersMadeByUserResponse.FromString,
                )
        self.AcceptOffer = channel.unary_unary(
                '/protobuf.Network/AcceptOffer',
                request_serializer=network__pb2.AcceptOfferRequest.SerializeToString,
                response_deserializer=network__pb2.AcceptOfferResponse.FromString,
                )


class NetworkServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SaveImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitItemOffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNetworksForUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItemsForUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItemsForNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOffersForUserItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOffersMadeByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptOffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NetworkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveImage': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveImage,
                    request_deserializer=network__pb2.SaveImageRequest.FromString,
                    response_serializer=network__pb2.SaveImageResponse.SerializeToString,
            ),
            'GetImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImage,
                    request_deserializer=network__pb2.GetImageRequest.FromString,
                    response_serializer=network__pb2.GetImageResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=network__pb2.CreateUserRequest.FromString,
                    response_serializer=network__pb2.CreateUserResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=network__pb2.GetUserRequest.FromString,
                    response_serializer=network__pb2.GetUserResponse.SerializeToString,
            ),
            'SubmitItem': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitItem,
                    request_deserializer=network__pb2.SubmitItemRequest.FromString,
                    response_serializer=network__pb2.SubmitItemResponse.SerializeToString,
            ),
            'SubmitItemOffer': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitItemOffer,
                    request_deserializer=network__pb2.SubmitItemOfferRequest.FromString,
                    response_serializer=network__pb2.SubmitItemOfferResponse.SerializeToString,
            ),
            'CreateNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNetwork,
                    request_deserializer=network__pb2.CreateNetworkRequest.FromString,
                    response_serializer=network__pb2.CreateNetworkResponse.SerializeToString,
            ),
            'GetNetworksForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetworksForUser,
                    request_deserializer=network__pb2.GetNetworksForUserRequest.FromString,
                    response_serializer=network__pb2.GetNetworksForUserResponse.SerializeToString,
            ),
            'GetItemsForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItemsForUser,
                    request_deserializer=network__pb2.GetItemsForUserRequest.FromString,
                    response_serializer=network__pb2.GetItemsForUserResponse.SerializeToString,
            ),
            'GetItemsForNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItemsForNetwork,
                    request_deserializer=network__pb2.GetItemsForNetworkRequest.FromString,
                    response_serializer=network__pb2.GetItemsForNetworkResponse.SerializeToString,
            ),
            'JoinNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinNetwork,
                    request_deserializer=network__pb2.JoinNetworkRequest.FromString,
                    response_serializer=network__pb2.JoinNetworkResponse.SerializeToString,
            ),
            'GetOffersForUserItems': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOffersForUserItems,
                    request_deserializer=network__pb2.GetOffersForUserItemsRequest.FromString,
                    response_serializer=network__pb2.GetOffersForUserItemsResponse.SerializeToString,
            ),
            'GetOffersMadeByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOffersMadeByUser,
                    request_deserializer=network__pb2.GetOffersMadeByUserRequest.FromString,
                    response_serializer=network__pb2.GetOffersMadeByUserResponse.SerializeToString,
            ),
            'AcceptOffer': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptOffer,
                    request_deserializer=network__pb2.AcceptOfferRequest.FromString,
                    response_serializer=network__pb2.AcceptOfferResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protobuf.Network', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Network(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/SaveImage',
            network__pb2.SaveImageRequest.SerializeToString,
            network__pb2.SaveImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/GetImage',
            network__pb2.GetImageRequest.SerializeToString,
            network__pb2.GetImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/CreateUser',
            network__pb2.CreateUserRequest.SerializeToString,
            network__pb2.CreateUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/GetUser',
            network__pb2.GetUserRequest.SerializeToString,
            network__pb2.GetUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubmitItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/SubmitItem',
            network__pb2.SubmitItemRequest.SerializeToString,
            network__pb2.SubmitItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubmitItemOffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/SubmitItemOffer',
            network__pb2.SubmitItemOfferRequest.SerializeToString,
            network__pb2.SubmitItemOfferResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/CreateNetwork',
            network__pb2.CreateNetworkRequest.SerializeToString,
            network__pb2.CreateNetworkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNetworksForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/GetNetworksForUser',
            network__pb2.GetNetworksForUserRequest.SerializeToString,
            network__pb2.GetNetworksForUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetItemsForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/GetItemsForUser',
            network__pb2.GetItemsForUserRequest.SerializeToString,
            network__pb2.GetItemsForUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetItemsForNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/GetItemsForNetwork',
            network__pb2.GetItemsForNetworkRequest.SerializeToString,
            network__pb2.GetItemsForNetworkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def JoinNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/JoinNetwork',
            network__pb2.JoinNetworkRequest.SerializeToString,
            network__pb2.JoinNetworkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOffersForUserItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/GetOffersForUserItems',
            network__pb2.GetOffersForUserItemsRequest.SerializeToString,
            network__pb2.GetOffersForUserItemsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOffersMadeByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/GetOffersMadeByUser',
            network__pb2.GetOffersMadeByUserRequest.SerializeToString,
            network__pb2.GetOffersMadeByUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AcceptOffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/AcceptOffer',
            network__pb2.AcceptOfferRequest.SerializeToString,
            network__pb2.AcceptOfferResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
