# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import network_pb2 as network__pb2


class NetworkStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveImage = channel.unary_unary(
                '/protobuf.Network/SaveImage',
                request_serializer=network__pb2.SaveImageRequest.SerializeToString,
                response_deserializer=network__pb2.SaveImageResponse.FromString,
                )
        self.GetImage = channel.unary_unary(
                '/protobuf.Network/GetImage',
                request_serializer=network__pb2.GetImageRequest.SerializeToString,
                response_deserializer=network__pb2.GetImageResponse.FromString,
                )
        self.CreateUser = channel.unary_unary(
                '/protobuf.Network/CreateUser',
                request_serializer=network__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=network__pb2.CreateUserResponse.FromString,
                )
        self.GetUser = channel.unary_unary(
                '/protobuf.Network/GetUser',
                request_serializer=network__pb2.GetUserRequest.SerializeToString,
                response_deserializer=network__pb2.GetUserResponse.FromString,
                )
        self.SearchForUser = channel.unary_unary(
                '/protobuf.Network/SearchForUser',
                request_serializer=network__pb2.SearchForUserRequest.SerializeToString,
                response_deserializer=network__pb2.SearchForUserResponse.FromString,
                )
        self.CreateFriendship = channel.unary_unary(
                '/protobuf.Network/CreateFriendship',
                request_serializer=network__pb2.CreateFriendshipRequest.SerializeToString,
                response_deserializer=network__pb2.CreateFriendshipResponse.FromString,
                )
        self.ReplyToFriendship = channel.unary_unary(
                '/protobuf.Network/ReplyToFriendship',
                request_serializer=network__pb2.ReplyToFriendshipRequest.SerializeToString,
                response_deserializer=network__pb2.ReplyToFriendshipResponse.FromString,
                )
        self.SubmitItem = channel.unary_unary(
                '/protobuf.Network/SubmitItem',
                request_serializer=network__pb2.SubmitItemRequest.SerializeToString,
                response_deserializer=network__pb2.SubmitItemResponse.FromString,
                )
        self.SubmitItemOffer = channel.unary_unary(
                '/protobuf.Network/SubmitItemOffer',
                request_serializer=network__pb2.SubmitItemOfferRequest.SerializeToString,
                response_deserializer=network__pb2.SubmitItemOfferResponse.FromString,
                )
        self.CreateNetwork = channel.unary_unary(
                '/protobuf.Network/CreateNetwork',
                request_serializer=network__pb2.CreateNetworkRequest.SerializeToString,
                response_deserializer=network__pb2.CreateNetworkResponse.FromString,
                )
        self.GetNetworksForUser = channel.unary_unary(
                '/protobuf.Network/GetNetworksForUser',
                request_serializer=network__pb2.GetNetworksForUserRequest.SerializeToString,
                response_deserializer=network__pb2.GetNetworksForUserResponse.FromString,
                )
        self.GetItemsForUser = channel.unary_unary(
                '/protobuf.Network/GetItemsForUser',
                request_serializer=network__pb2.GetItemsForUserRequest.SerializeToString,
                response_deserializer=network__pb2.GetItemsForUserResponse.FromString,
                )
        self.GetItemsForNetwork = channel.unary_unary(
                '/protobuf.Network/GetItemsForNetwork',
                request_serializer=network__pb2.GetItemsForNetworkRequest.SerializeToString,
                response_deserializer=network__pb2.GetItemsForNetworkResponse.FromString,
                )
        self.SearchForNetworks = channel.unary_unary(
                '/protobuf.Network/SearchForNetworks',
                request_serializer=network__pb2.SearchForNetworksRequest.SerializeToString,
                response_deserializer=network__pb2.SearchForNetworksResponse.FromString,
                )
        self.InviteUserToNetwork = channel.unary_unary(
                '/protobuf.Network/InviteUserToNetwork',
                request_serializer=network__pb2.InviteUserToNetworkRequest.SerializeToString,
                response_deserializer=network__pb2.InviteUserToNetworkResponse.FromString,
                )
        self.ReplyToNetworkInvite = channel.unary_unary(
                '/protobuf.Network/ReplyToNetworkInvite',
                request_serializer=network__pb2.ReplyToNetworkInviteRequest.SerializeToString,
                response_deserializer=network__pb2.ReplyToNetworkInviteResponse.FromString,
                )
        self.JoinNetwork = channel.unary_unary(
                '/protobuf.Network/JoinNetwork',
                request_serializer=network__pb2.JoinNetworkRequest.SerializeToString,
                response_deserializer=network__pb2.JoinNetworkResponse.FromString,
                )
        self.GetOffersForUser = channel.unary_unary(
                '/protobuf.Network/GetOffersForUser',
                request_serializer=network__pb2.GetOffersForUserRequest.SerializeToString,
                response_deserializer=network__pb2.GetOffersForUserResponse.FromString,
                )


class NetworkServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SaveImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchForUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFriendship(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplyToFriendship(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitItemOffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNetworksForUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItemsForUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItemsForNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchForNetworks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InviteUserToNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplyToNetworkInvite(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOffersForUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NetworkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveImage': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveImage,
                    request_deserializer=network__pb2.SaveImageRequest.FromString,
                    response_serializer=network__pb2.SaveImageResponse.SerializeToString,
            ),
            'GetImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImage,
                    request_deserializer=network__pb2.GetImageRequest.FromString,
                    response_serializer=network__pb2.GetImageResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=network__pb2.CreateUserRequest.FromString,
                    response_serializer=network__pb2.CreateUserResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=network__pb2.GetUserRequest.FromString,
                    response_serializer=network__pb2.GetUserResponse.SerializeToString,
            ),
            'SearchForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchForUser,
                    request_deserializer=network__pb2.SearchForUserRequest.FromString,
                    response_serializer=network__pb2.SearchForUserResponse.SerializeToString,
            ),
            'CreateFriendship': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFriendship,
                    request_deserializer=network__pb2.CreateFriendshipRequest.FromString,
                    response_serializer=network__pb2.CreateFriendshipResponse.SerializeToString,
            ),
            'ReplyToFriendship': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplyToFriendship,
                    request_deserializer=network__pb2.ReplyToFriendshipRequest.FromString,
                    response_serializer=network__pb2.ReplyToFriendshipResponse.SerializeToString,
            ),
            'SubmitItem': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitItem,
                    request_deserializer=network__pb2.SubmitItemRequest.FromString,
                    response_serializer=network__pb2.SubmitItemResponse.SerializeToString,
            ),
            'SubmitItemOffer': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitItemOffer,
                    request_deserializer=network__pb2.SubmitItemOfferRequest.FromString,
                    response_serializer=network__pb2.SubmitItemOfferResponse.SerializeToString,
            ),
            'CreateNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNetwork,
                    request_deserializer=network__pb2.CreateNetworkRequest.FromString,
                    response_serializer=network__pb2.CreateNetworkResponse.SerializeToString,
            ),
            'GetNetworksForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNetworksForUser,
                    request_deserializer=network__pb2.GetNetworksForUserRequest.FromString,
                    response_serializer=network__pb2.GetNetworksForUserResponse.SerializeToString,
            ),
            'GetItemsForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItemsForUser,
                    request_deserializer=network__pb2.GetItemsForUserRequest.FromString,
                    response_serializer=network__pb2.GetItemsForUserResponse.SerializeToString,
            ),
            'GetItemsForNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItemsForNetwork,
                    request_deserializer=network__pb2.GetItemsForNetworkRequest.FromString,
                    response_serializer=network__pb2.GetItemsForNetworkResponse.SerializeToString,
            ),
            'SearchForNetworks': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchForNetworks,
                    request_deserializer=network__pb2.SearchForNetworksRequest.FromString,
                    response_serializer=network__pb2.SearchForNetworksResponse.SerializeToString,
            ),
            'InviteUserToNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.InviteUserToNetwork,
                    request_deserializer=network__pb2.InviteUserToNetworkRequest.FromString,
                    response_serializer=network__pb2.InviteUserToNetworkResponse.SerializeToString,
            ),
            'ReplyToNetworkInvite': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplyToNetworkInvite,
                    request_deserializer=network__pb2.ReplyToNetworkInviteRequest.FromString,
                    response_serializer=network__pb2.ReplyToNetworkInviteResponse.SerializeToString,
            ),
            'JoinNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinNetwork,
                    request_deserializer=network__pb2.JoinNetworkRequest.FromString,
                    response_serializer=network__pb2.JoinNetworkResponse.SerializeToString,
            ),
            'GetOffersForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOffersForUser,
                    request_deserializer=network__pb2.GetOffersForUserRequest.FromString,
                    response_serializer=network__pb2.GetOffersForUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protobuf.Network', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Network(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/SaveImage',
            network__pb2.SaveImageRequest.SerializeToString,
            network__pb2.SaveImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/GetImage',
            network__pb2.GetImageRequest.SerializeToString,
            network__pb2.GetImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/CreateUser',
            network__pb2.CreateUserRequest.SerializeToString,
            network__pb2.CreateUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/GetUser',
            network__pb2.GetUserRequest.SerializeToString,
            network__pb2.GetUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/SearchForUser',
            network__pb2.SearchForUserRequest.SerializeToString,
            network__pb2.SearchForUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateFriendship(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/CreateFriendship',
            network__pb2.CreateFriendshipRequest.SerializeToString,
            network__pb2.CreateFriendshipResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplyToFriendship(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/ReplyToFriendship',
            network__pb2.ReplyToFriendshipRequest.SerializeToString,
            network__pb2.ReplyToFriendshipResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubmitItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/SubmitItem',
            network__pb2.SubmitItemRequest.SerializeToString,
            network__pb2.SubmitItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubmitItemOffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/SubmitItemOffer',
            network__pb2.SubmitItemOfferRequest.SerializeToString,
            network__pb2.SubmitItemOfferResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/CreateNetwork',
            network__pb2.CreateNetworkRequest.SerializeToString,
            network__pb2.CreateNetworkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNetworksForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/GetNetworksForUser',
            network__pb2.GetNetworksForUserRequest.SerializeToString,
            network__pb2.GetNetworksForUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetItemsForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/GetItemsForUser',
            network__pb2.GetItemsForUserRequest.SerializeToString,
            network__pb2.GetItemsForUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetItemsForNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/GetItemsForNetwork',
            network__pb2.GetItemsForNetworkRequest.SerializeToString,
            network__pb2.GetItemsForNetworkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchForNetworks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/SearchForNetworks',
            network__pb2.SearchForNetworksRequest.SerializeToString,
            network__pb2.SearchForNetworksResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InviteUserToNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/InviteUserToNetwork',
            network__pb2.InviteUserToNetworkRequest.SerializeToString,
            network__pb2.InviteUserToNetworkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplyToNetworkInvite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/ReplyToNetworkInvite',
            network__pb2.ReplyToNetworkInviteRequest.SerializeToString,
            network__pb2.ReplyToNetworkInviteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def JoinNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/JoinNetwork',
            network__pb2.JoinNetworkRequest.SerializeToString,
            network__pb2.JoinNetworkResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOffersForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.Network/GetOffersForUser',
            network__pb2.GetOffersForUserRequest.SerializeToString,
            network__pb2.GetOffersForUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
